const ProductData =[
    {
        id: 0,
        img: "/shoe1.jpg",
        name: "WhiteLoom",
        price: 29.99,
        category: ["Men's Shoes"],
        sale: false,
    },
    {
        id: 1,
        img: "/shoe2.jpg",
        name: "Casual Shoes",
        price: 30.99,
        category: ["Men's Shoes"],
        sale: false,
    },
    {
        id: 2,
        img: "/shoe4.jpg",
        name: "Sneakers",
        price: 28.99,
        category: ["Men's Shoes"],
        sale: true,
    },
    {
        id: 3,
        img: "/shoe6.jpg",
        name: "Pure Leather",
        price: 25.00,
        category: ["Men's Shoes"],
        sale: true,
    },

    {
        id: 4,
        img: "/watch2.jpg",
        name: "Quartz Watch",
        price:  30.00,
        category: ["Watche's"],
        sale: false,
    },
    {
        id: 5,
        img: "/watch3.jpg",
        name: "Masculino Watch",
        price: 32.00,
        category: ["Watche's"],
        sale: false,
    },
    {
        id: 6,
        img: "/watch4.jpg",
        name: "Stylish Watch",
        price: 35.00,
        category: ["Watche's"],
        sale: false,
    },
    {
        id: 7,
        img: "/watch7.jpg",
        name: "Luxury Watch",
        price: 30.00,
        category: ["Watche's"],
        sale: true,
    },
    {
        id: 8,
        img: "/watch6.jpg",
        name: "Stylish Watch",
        price: 32.00,
        category: ["Watche's"],
        sale: true,
    },
    {
        id: 9,
        img: "/shoes2.jpg",
        name: "Sneakers",
        price: 30.00,
        category: ["woman's shoes"],
        sale: false,
    },
    {
        id: 10,
        img: "/shoes3.jpg",
        name: "Casual Shoes",
        price: 35.00,
        category: ["woman's shoes"],
        sale: true,
    },
    {
        id: 11,
        img: "/shoes4.jpg",
        name: "Corian Sneakers",
        price: 35.00,
        category: ["woman's shoes"],
        sale: true,
    },
    {
        id: 12,
        img: "/kid2.jpg",
        name: "Sneakers",
        price: 20.00,
        category: ["Kid's Shoes"],
        sale: false,
    },
    {
        id: 13,
        img: "/kid4.jpg",
        name: "Pink Light Up Shoes",
        price: 25.00,
        category: ["Kid's Shoes"],
        sale: false,
    },
    {
        id: 14,
        img: "/kid3.jpg",
        name: "Light Up Shoes",
        price: 24.00,
        category: ["Kid's Shoes"],
        sale: true,
    },
    {
        id: 15,
        img: "/kid5.jpg",
        name: "Pink Light Up Roler Shoes",
        price: 24.00,
        category: ["Kid's Shoes"],
        sale: true,
    },
    {
        id: 16,
        img: "/kid1.jpg",
        name: "Cute Baby Shoes",
        price: 20.00,
        category: ["Kid's Shoes"],
        sale: true,
    },
    {
        id: 17,
        img: "/woman1.jpg",
        name: "Trending Dress",
        price: 30.00,
        category: ["Clothe's"],
        sale: true,
    },
    {
        id: 18,
        img: "/woman2.jpg",
        name: " Stylish Dress",
        price: 29.99,
        category: ["Clothe's"],
        sale: false,
    },
    {
        id: 19,
        img: "/woman3.jpg",
        name: "Trending Dress",
        price: 22.99,
        category: ["Clothe's"],
        sale: true,
    },
    {
        id: 20,
        img: "/woman4.jpg",
        name: "Stylish Dress",
        price: 24.99,
        category: ["Clothe's"],
        sale: true,
    },
    {
        id: 21,
        img: "/dress2.jpg",
        name: "Stylish Dress",
        price: 25.99,
        category: ["Clothe's"],
        sale: false,
    },
    {
        id: 22,
        img: "/dress6.jpg",
        name: "Tranding Dress",
        price: 29.99,
        category: ["Clothe's"],
        sale: true,
    },
    {
        id: 23,
        img: "/dress8.jpg",
        name: "Stylish Dress",
        price: 25.99,
        category: ["Clothe's"],
        sale: false,
    },
    {
        id: 24,
        img: "/dress4.jpg",
        name: "New Dress",
        price: 23.99,
        category: ["Clothe's"],
        sale: true,
    },
    {
        id: 25,
        img: "/jacket1.jpg",
        name: "Stylish Jacket",
        price: 29.99,
        category: ["Clothe's"],
        sale: true,
    },
    {
        id: 26,
        img: "/jacket2.jpg",
        name: "Tranding Jacket",
        price: 30.00,
        category: ["Clothe's"],
        sale: false,
    },
    {
        id: 27,
        img: "/jewellery1.jpg",
        name: "Gold Plated Pearl Necklace",
        price: 50.00,
        category: ["Jewellery's"],
        sale: true,
    },
    {
        id: 28,
        img: "/jewellery2.jpg",
        name: "Diamond Jewellery Set",
        price: 100.00,
        category: ["Jewellery's"],
        sale: true,
    },
    {
        id: 29,
        img: "/jewellery3.jpg",
        name: "heart shaped locket set",
        price: 40.00,
        category: ["Jewellery's"],
        sale: false,
    },
    {
        id: 30,
        img: "/jewellery4.jpg",
        name: "Girls Name Jewellery Set",
        price: 35.00,
        category: ["Jewellery's"],
        sale: true,
    },
    {
        id: 31,
        img: "/perfume1.jpg",
        name: "Aqua Marine",
        price: 30.00,
        category: ["Perfume's"],
        sale: true,
    },
    {
        id: 32,
        img: "/perfume2.jpg",
        name: "Dream Angels Wings Perfume",
        price: 35.00,
        category: ["Perfume's"],
        sale: true,
    },
    {
        id: 33,
        img: "/perfume3.jpg",
        name: "Best female perfumes",
        price: 32.00,
        category: ["Perfume's"],
        sale: false,
    },
    {
        id: 34,
        img: "/perfume4.jpg",
        name: "Elixir-perfume Men",
        price: 35.00,
        category: ["Perfume's"],
        sale: true,
    },
    {
        id: 35,
        img: "/perfume5.jpg",
        name: "Flore De Paris Eau De Perfume",
        price: 33.00,
        category: ["Perfume's"],
        sale: false,
    },
]
export default ProductData